# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import telemetry_pb2 as proto_dot_telemetry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub(object):
    """------------------------------------
    Services
    ------------------------------------
    Sensors push measurements continuously to collectors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMeasurements = channel.stream_unary(
                '/telemetry.v1.IngestService/PushMeasurements',
                request_serializer=proto_dot_telemetry__pb2.Measurement.SerializeToString,
                response_deserializer=proto_dot_telemetry__pb2.IngestAck.FromString,
                _registered_method=True)


class IngestServiceServicer(object):
    """------------------------------------
    Services
    ------------------------------------
    Sensors push measurements continuously to collectors.
    """

    def PushMeasurements(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMeasurements': grpc.stream_unary_rpc_method_handler(
                    servicer.PushMeasurements,
                    request_deserializer=proto_dot_telemetry__pb2.Measurement.FromString,
                    response_serializer=proto_dot_telemetry__pb2.IngestAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService(object):
    """------------------------------------
    Services
    ------------------------------------
    Sensors push measurements continuously to collectors.
    """

    @staticmethod
    def PushMeasurements(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/telemetry.v1.IngestService/PushMeasurements',
            proto_dot_telemetry__pb2.Measurement.SerializeToString,
            proto_dot_telemetry__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AggregateServiceStub(object):
    """FastAPI (or any consumer) can stream aggregate updates from collectors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAggregates = channel.unary_stream(
                '/telemetry.v1.AggregateService/StreamAggregates',
                request_serializer=proto_dot_telemetry__pb2.StreamAggregatesRequest.SerializeToString,
                response_deserializer=proto_dot_telemetry__pb2.Aggregate.FromString,
                _registered_method=True)


class AggregateServiceServicer(object):
    """FastAPI (or any consumer) can stream aggregate updates from collectors.
    """

    def StreamAggregates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAggregates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAggregates,
                    request_deserializer=proto_dot_telemetry__pb2.StreamAggregatesRequest.FromString,
                    response_serializer=proto_dot_telemetry__pb2.Aggregate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.v1.AggregateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.v1.AggregateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AggregateService(object):
    """FastAPI (or any consumer) can stream aggregate updates from collectors.
    """

    @staticmethod
    def StreamAggregates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/telemetry.v1.AggregateService/StreamAggregates',
            proto_dot_telemetry__pb2.StreamAggregatesRequest.SerializeToString,
            proto_dot_telemetry__pb2.Aggregate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryServiceStub(object):
    """FastAPI (or any client) can query on-demand stats, e.g. per sensor_id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSensorStats = channel.unary_unary(
                '/telemetry.v1.QueryService/GetSensorStats',
                request_serializer=proto_dot_telemetry__pb2.GetSensorStatsRequest.SerializeToString,
                response_deserializer=proto_dot_telemetry__pb2.GetSensorStatsResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """FastAPI (or any client) can query on-demand stats, e.g. per sensor_id.
    """

    def GetSensorStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSensorStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorStats,
                    request_deserializer=proto_dot_telemetry__pb2.GetSensorStatsRequest.FromString,
                    response_serializer=proto_dot_telemetry__pb2.GetSensorStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """FastAPI (or any client) can query on-demand stats, e.g. per sensor_id.
    """

    @staticmethod
    def GetSensorStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telemetry.v1.QueryService/GetSensorStats',
            proto_dot_telemetry__pb2.GetSensorStatsRequest.SerializeToString,
            proto_dot_telemetry__pb2.GetSensorStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
